name: amap_core_fluttify
description: An `Amap` Core Component, Powered By `Fluttify` Engine, A Dart Bindings Generator For Native SDK.
version: 0.13.0+1
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_core_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify: ^0.11.0-dev.0
  core_location_fluttify: ^0.6.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_core_fluttify
        pluginClass: AmapCoreFluttifyPlugin
      ios:
        pluginClass: AmapCoreFluttifyPlugin